### ISSUE TITLE
Insert only takes 3 args

### ISSUE THREAD

**Issue by Moosems** [rdbende/tkcode#18]
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/Moosems/Desktop/DIP-dev/LangEditors.py", line 135, in _autocomplete
    self.insert(insert, remainder, ("sel", "autocomplete"))
TypeError: BaseCodeBox.insert() takes 3 positional arguments but 4 were given
```

**Comment by Moosems** [comment]
Any thoughts?

**Comment by rdbende** [comment]
Yeah, indeed. Atm it takes only 3 arguments. I forgot to implement tag insertion.
